language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
services:
  - postgresql
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.6
  - sudo pip install pipenv
  - pipenv install
before_script:
  - echo "DATABASE_URL=postgres://postgres@localhost/pandas_sports" > .env
  - cargo install diesel_cli --no-default-features --features=postgres
  - diesel database setup
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run &
  - SERVER_PID=$!
  - python test.py
  - kill $!
