language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
services:
  - postgresql
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - pip3 install -r requirements.txt
before_script:
  - touch .env
  - echo "ADMIN_PASS=admin" >> .env
  - echo "COOKIE_KEY=$(head /dev/urandom | tr -dc A-Za-z | head -c 32)" >> .env
  - echo "DATABASE_URL=postgres://postgres@localhost/pandas_sports" >> .env
  - echo "DOMAIN=0.0.0.0" >> .env
  - echo "PEPPER=$(head /dev/urandom | tr -dc A-Za-z | head -c 32)" >> .env
  - echo "PORT=8080" >> .env
  - cargo install --force diesel_cli --no-default-features --features=postgres
  - diesel database setup
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run &
  - SERVER_PID=$!
  - python3 test.py
  - kill $!
